"""Stage: baatcheet_visuals — fills `visual_explanation` slots on the
dialogue's `visual` cards with PixiJS code generated by `PixiCodeGenerator`.

Phase 4 will refactor this stage's runtime to fold in the V2 visual-pass
selector. Phase 1 keeps the existing behaviour exactly.
"""
from __future__ import annotations

from book_ingestion_v2.constants import V2JobType
from book_ingestion_v2.dag.status_helpers import (
    build_blocked,
    build_stage,
    latest_job_for_guideline,
    overlay_job_state,
)
from book_ingestion_v2.dag.types import (
    Stage,
    StageScope,
    StageStatusOutput,
    StatusContext,
)
from book_ingestion_v2.services.stage_launchers import launch_baatcheet_visual_job


_JOB_TYPE = V2JobType.BAATCHEET_VISUAL_ENRICHMENT.value


def _status(ctx: StatusContext) -> StageStatusOutput:
    from shared.repositories.dialogue_repository import DialogueRepository

    repo = DialogueRepository(ctx.db)
    dialogue = repo.get_by_guideline_id(ctx.guideline_id)
    job = latest_job_for_guideline(
        ctx.db, guideline_id=ctx.guideline_id, job_type=_JOB_TYPE
    )
    if not dialogue or not dialogue.cards_json:
        return build_blocked(
            "baatcheet_visuals", blocked_by="baatcheet_dialogue", job=job,
        )

    total_visual_cards = 0
    cards_with_visuals = 0
    for card in dialogue.cards_json:
        if isinstance(card, dict) and card.get("card_type") == "visual":
            total_visual_cards += 1
            ve = card.get("visual_explanation")
            if isinstance(ve, dict) and ve.get("pixi_code"):
                cards_with_visuals += 1

    if total_visual_cards == 0:
        # No visual cards on this dialogue — Stage 5c is trivially "done".
        return build_stage(
            "baatcheet_visuals", "done",
            "No visual cards in this dialogue", [], job=job,
        )

    artifact_present = cards_with_visuals > 0
    if cards_with_visuals == total_visual_cards:
        state = "done"
    elif cards_with_visuals > 0:
        state = "warning"
    else:
        state = "ready"
    summary = f"{cards_with_visuals}/{total_visual_cards} visual cards have PixiJS"

    state, summary, warnings = overlay_job_state(
        state=state, summary=summary, warnings=[],
        job=job, artifact_present=artifact_present,
    )
    return build_stage("baatcheet_visuals", state, summary, warnings, job=job)


STAGE = Stage(
    id="baatcheet_visuals",
    scope=StageScope.TOPIC,
    label="Baatcheet Visuals",
    depends_on=("baatcheet_dialogue",),
    launch=launch_baatcheet_visual_job,
    status_check=_status,
)
